[package]
name = "egor"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "demos/secs_particles",
    "demos/shooter"
]
resolver = "2"

[features]
default = []
webgl = ["wgpu/webgl"]
log = ["dep:log", "dep:env_logger", "dep:console_log", "dep:console_error_panic_hook"]

[dependencies]
bytemuck = "1.23.0"
glyphon = "0.9.0"
image = "0.25.6"
log = { version = "0.4.27", optional = true }
wgpu = "25.0.0"
winit = "0.30.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = { version = "1.0.0", optional = true }
web-sys = { version = "0.3.77", features = ["Window", "Performance"]}
wasm-bindgen-futures = "0.4.50"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = { version = "0.11.8", optional = true }
pollster = "0.4.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
